---
- name: timesync role
  hosts: all
  become: yes
  vars:
    timesync_ntp_provider: chrony
    timesync_ntp_servers:
      - hostname: 172.25.254.254
        iburst: yes
  roles:
    - redhat.rhel_system_roles.timesync
